services:
  identityserviceapi.gateway:
    image: ${DOCKER_REGISTRY-}identityserviceapi.gateway
    build:
      context: src/IdentityServiceApi.Gateway
      dockerfile: Dockerfile

  identityserviceapi:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: src/IdentityServiceApi
      dockerfile: Dockerfile
