using IdentityServiceApi.Services.CacheKeys;

namespace IdentityServiceApi.Tests.Unit.Services.CacheKeys
{
    /// <summary>
    ///     Unit tests for the <see cref="UserCacheKeyService"/> class.
    ///     These tests validate the behavior of user list key generation, tracking, and clearing logic.
    /// </summary>
    /// <remarks>
    ///     @Author: Christian Briglio
    ///     @Created: 2025
    /// </remarks>
    [Trait("TestCategory", "UnitTest")]
    public class UserCacheKeyServiceTests
    {
        private readonly UserCacheKeyService _service = new();

        /// <summary>
        ///     Verifies that the <see cref="UserCacheKeyService.CreationStatsKey"/> property
        ///     returns the expected constant key format for creation statistics.
        /// </summary>
        [Fact]
        public void CreationStatsKey_ReturnsCorrectKey()
        {
            // Act
            var key = _service.CreationStatsKey;

            // Assert
            Assert.Equal("user:creation-stats", key);
        }

        /// <summary>
        ///     Verifies that the <see cref="UserCacheKeyService.StateMetricsKey"/> property
        ///     returns the expected constant key format for user state metrics.
        /// </summary>
        [Fact]
        public void StateMetricsKey_ReturnsCorrectKey()
        {
            // Act
            var key = _service.StateMetricsKey;

            // Assert
            Assert.Equal("user:state-metrics", key);
        }

        /// <summary>
        ///     Verifies that the <see cref="UserCacheKeyService.GetUserListKey(int, int, int?)"/>
        ///     method generates a properly formatted key string with a non-null account status.
        /// </summary>
        [Fact]
        public void GetUserListKey_WithAccountStatus_ReturnsCorrectKey()
        {
            // Arrange
            int page = 1;
            int pageSize = 20;
            int? status = 1;

            // Act
            var key = _service.GetUserListKey(page, pageSize, status);

            // Assert
            Assert.Equal("user:list:Page:1:size:20:status:1", key);
        }

        /// <summary>
        ///     Verifies that the <see cref="UserCacheKeyService.GetUserListKey(int, int, int?)"/>
        ///     method includes "null" in the key when no account status is specified.
        /// </summary>
        [Fact]
        public void GetUserListKey_WithoutAccountStatus_IncludesNullInKey()
        {
            // Arrange
            int page = 2;
            int pageSize = 15;
            int? status = null;

            // Act
            var key = _service.GetUserListKey(page, pageSize, status);

            // Assert
            Assert.Equal("user:list:Page:2:size:15:status:null", key);
        }

        /// <summary>
        ///     Verifies that the <see cref="UserCacheKeyService.GetAllUserListKeys"/> method
        ///     returns all previously tracked user list keys generated by the service.
        /// </summary>
        [Fact]
        public void GetAllUserListKeys_ReturnsAllTrackedKeys()
        {
            // Arrange
            _service.ClearTrackedKeys(); // Start from a clean state
            var key1 = _service.GetUserListKey(1, 10, 0);
            var key2 = _service.GetUserListKey(2, 25, null);

            // Act
            var keys = _service.GetAllUserListKeys().ToList();

            // Assert
            Assert.Contains(key1, keys);
            Assert.Contains(key2, keys);
            Assert.Equal(2, keys.Count);
        }

        /// <summary>
        ///     Verifies that the <see cref="UserCacheKeyService.ClearTrackedKeys"/> method
        ///     removes all entries from the tracked user list cache keys collection.
        /// </summary>
        [Fact]
        public void ClearTrackedKeys_RemovesAllKeys()
        {
            // Arrange
            _service.GetUserListKey(1, 10, 1);
            _service.GetUserListKey(3, 30, 0);

            // Act
            _service.ClearTrackedKeys();
            var keys = _service.GetAllUserListKeys();

            // Assert
            Assert.Empty(keys);
        }
    }
}
