using IdentityServiceApi.Shared.ResultFactories;

namespace IdentityServiceApi.Features.Authentication.Models
{
    /// <summary>
    ///     Represents the result of a login-related operation performed by the login service.
    /// </summary>
    /// <remarks>
    ///     @Author: Christian Briglio
    ///     @Created: 2024
    ///     @Updated: 2026
    /// </remarks>
    public class LoginResult : Result
    {
        /// <summary>
        ///     Token generated by login service after user is successfully authenticated.
        /// </summary>
        public string? Token { get; set; }
    }
}
